package edu.arizona.biosemantics.etcsitehelp.shared.help;

public enum Help {

	GETTING_STARTED,
	TASK_MANAGER,
	FILE_MANAGER,
	MY_ACCOUNT,
	TEXT_CAPTURE_CREATE,
	TEXT_CAPTURE_INPUT,
	TEXT_CAPTURE_PREPROCESS,
	TEXT_CAPTURE_LEARN,
	TEXT_CAPTURE_REVIEW,
	TEXT_CAPTURE_PARSE,
	TEXT_CAPTURE_OUTPUT,
	MATRIX_GENERATION_CREATE,
	MATRIX_GENERATION_INPUT,
	MATRIX_GENERATION_PROCESS,
	MATRIX_GENERATION_REVIEW,
	MATRIX_GENERATION_OUTPUT,
	ONTOLOGY_BUILDING_CREATE,
	ONTOLOGY_BUILDING_INPUT,
	ONTOLOGY_BUILDING_BUILD,
	ONTOLOGY_BUILDING_OUTPUT,
	TREE_GENERATION_CREATE,
	TREE_GENERATION_INPUT,
	TREE_GENERATION_VIEW,
	TAXONOMY_COMPARISON_CREATE,
	TAXONOMY_COMPARISON_INPUT,
	TAXONOMY_COMPARISON_ALIGN;
	
}
