package edu.arizona.biosemantics.etcsitehelp.shared.help;

public enum Help {

	FILE_MANAGER,
	GETTING_STARTED,
	
	MATRIX_GENERATION_DEFINE,
	MATRIX_GENERATION_INPUT,
	MATRIX_GENERATION_PROCESS,
	MATRIX_GENERATION_REVIEW,
	MATRIX_GENERATION_OUTPUT,

	MY_ACCOUNT,
	ONTOLOGY_BUILDING_BUILD,
	ONTOLOGY_BUILDING_DEFINE,
	ONTOLOGY_BUILDING_INPUT,
	ONTOLOGY_BUILDING_OUTPUT,
	
	TASK_MANAGER,
	TAXONOMY_COMPARISON_ALIGN,
	TAXONOMY_COMPARISON_DEFINE,
	TAXONOMY_COMPARISON_INPUT,
	
	TEXT_CAPTURE_DEFINE,
	TEXT_CAPTURE_INPUT,
	TEXT_CAPTURE_PREPROCESS,
	TEXT_CAPTURE_LEARN,
	TEXT_CAPTURE_REVIEW,
	TEXT_CAPTURE_PARSE,
	TEXT_CAPTURE_OUTPUT,
	
	TREE_GENERATION_DEFINE,
	TREE_GENERATION_INPUT,
	TREE_GENERATION_VIEW,
	
	
}
