package edu.arizona.sirls.etc.site.client;

public enum HistoryState {
	HOME, 
	SETTINGS, 
	HELP, 
	FILE_MANAGER, 
	TASK_MANAGER, 
	VISUALIZATION, 
	TAXONOMY_COMPARISON, 
	TREE_GENERATION, 
	MATRIX_GENERATION,
	/*OUTPUT_MATRIX_GENERATION, 
	REVIEW_MATRIX_GENERATION, 
	PARSE_MATRIX_GENERATION, 
	LEARN_MATRIX_GENERATION, 
	PREPROCESS_MATRIX_GENERATION, 
	INPUT_MATRIX_GENERATION, */
	PIPELINE, MARKUP_REVIEW
}
